### ISSUE TITLE
Crash App when im trying to reload in debug mode

### ISSUE THREAD

**Issue by ducnguyen4301** [showtime-xyz/showtime-tab-view#10]
**react-native info**:
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 93.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/ducnguyen/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
   **Package**:
    "@showtime-xyz/tab-view": "^0.1.4",
    "@shopify/flash-list": "^1.4.3",
    "react-native-pager-view": "^6.2.0",
    "react-native-reanimated": "^2.7.0",
    "react-native-gesture-handler": "^2.9.0",
    

https://github.com/showtime-xyz/showtime-tab-view/assets/80993895/f00d6020-c3be-44f3-9602-1710586a5ea0

**Comment by ducnguyen4301** [comment]
I checking in flipper when app crashed appear message "**Invalidating <RCTCxxBridge: 0x14fd0a500> (parent: <RCTBridge: 0x60000335ca10>, executor: (null))**"

**Comment by alantoa** [comment]
hi @ducnguyen4301, this is a Reanimated & GestureHandler issue that has been ongoing for a long time. 
I just release a[ new version](https://github.com/showtime-xyz/showtime-tab-view/releases/tag/v0.1.5) for this, currently you can set `enableGestureRunOnJS ` to true in debug mode, I think this will avoid the crash.

**Comment by alantoa** [comment]
If you have already set it but it still crashes, I think it may be caused by other libraries.

**Comment by ducnguyen4301** [comment]
@alantoa great work, many thanks for it 🔥
