### ISSUE TITLE
how can i solve this problem？if i scroll the content,and when i change tabIndex,this content show at top...

### ISSUE THREAD

**Issue by Fengweiyuu** [showtime-xyz/showtime-tab-view#13]
https://github.com/showtime-xyz/showtime-tab-view/assets/11786678/10bd9053-15bc-45d3-bcb4-415d5673646d

**Comment by alantoa** [comment]
@Fengweiyuu Hey, can you try the v0.1.7 I just released?

**Comment by alantoa** [comment]
@Fengweiyuu  check here https://www.npmjs.com/package/@showtime-xyz/tab-view

**Comment by alantoa** [comment]
@Fengweiyuu oh i got it, you should correct part of your code to:
```
 renderScene={({ route: sceneRoute }) => {
    switch (sceneRoute.key) {
      case 'all':
        return (
          <ArticleRouteScene tabIndex={0} type="1" columnCode={columnCode} />
        )
      case 'video':
        return (
          <ArticleRouteScene tabIndex={1} type="2" columnCode={columnCode} />
        )
      case 'article':
        return (
          <ArticleRouteScene tabIndex={2} type="3" columnCode={columnCode} />
        )
      default:
        return null
    }
  }}
```

**Comment by alantoa** [comment]
And what is your "ArticleRouteScene" component code?

**Comment by alantoa** [comment]
try to update your tabIndex to see
https://github.com/showtime-xyz/showtime-tab-view/issues/13#issuecomment-1573217708
