### ISSUE TITLE
Multiple versions of a package were detected, ANNOYING !!!

### ISSUE THREAD

**Issue by abdullahIsa** [showtime-xyz/showtime-tab-view#16]
Hello this project is causing issues with others and kinda getting really annoying now, i have this issues mostly on ios 
i have already been able to bypass the error but i got no clue if its the cause of other errors for ios build, so please can you find solution to this, thanks.

![image](https://github.com/showtime-xyz/showtime-tab-view/assets/49385380/5b717120-2729-4962-9b4c-b1dcd6dca329)

**Comment by alantoa** [comment]
@abdullahIsa, hey, looks like it's related to your project dependencies, are you using npm or yarn?

**Comment by abdullahIsa** [comment]
> Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
> Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>
> Add a bulleted list, <Ctrl+Shift+8>Add a numbered list, <Ctrl+Shift+7>Add a task list, <Ctrl+Shift+l>
> Directly mention a user or team
> Reference an issue, pull request, or discussion
> Add saved reply
> Slash commands

i use npm, since showtime-tab-view  uses reanimated 3.1.0 it causes issue which it will say multiple version package and this leads other package that cant use 3.1.0 to throw error on XCode build which is why i had override it to 2.17.0 and all ok but i am facing an error in my XCode and i don't know how to fix and if the cause is from the reanimated issue or anything in the override and if i remember reanimated 3.1.0 has a fix for showtime-tab-view which means even if all builds well showtime-tab-view might not work as expected not sure, if i could revert all changes i would but i am already using showtime-tab-view in many screens.

for now i am just trying to find cause of below error.

![image](https://github.com/showtime-xyz/showtime-tab-view/assets/49385380/bfcba0b7-91fa-4ec9-b81e-1aaaa2900339)

**Comment by alantoa** [comment]
This component does not require reanimated v3, please try to clean your project and add reanimated to your overrides and try again!

**Comment by abdullahIsa** [comment]
> This component does not require reanimated v3, please try to clean your project and add reanimated to your overrides and try again!

apologies you right i had the latest version forgot why, in that case i dont know why i am getting Multiple versions of a package were detected but that has been solved, i am just trying to solve the error above "4 duplicate symbols...", you can close this issue, thanks.

![image](https://github.com/showtime-xyz/showtime-tab-view/assets/49385380/44959302-61d3-4830-90c5-531212012730)
