### ISSUE TITLE
Scrolling Entire container to Top?

### ISSUE THREAD

**Issue by aminerol** [showtime-xyz/showtime-tab-view#2]
can we have a ref for scrolling the container to top? Thank you

**Comment by alantoa** [comment]
Actually, I have already [added it to my TODO list](https://github.com/showtime-xyz/showtime-tab-view/blob/9a3d71793c9bfa00a59c56e204cdeb485812843a/src/create-collapsible-tabs.tsx#L66).
I will implement it when I have time.

**Comment by aminerol** [comment]
Thank you for the reply, this is my workaround for it if anyone was curious
```js
scrollToTop: () => {
  runOnUI(() => {
   'worklet'
   Object.values(childScrollRef).forEach(ref => {
     _ScrollTo(ref, 0, 0, false)
   })
 })()
}
```
