### ISSUE TITLE
Tried to register two views with the same name RNGestureHandlerButton 

### ISSUE THREAD

**Issue by sapjax** [showtime-xyz/showtime-tab-view#6]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/990255/235619604-0dc15d3c-790b-4dab-bc57-93553464fb0c.png">

I'm using expo, maybe related to https://github.com/software-mansion/react-native-gesture-handler/issues/451

**Comment by alantoa** [comment]
https://github.com/software-mansion/react-native-gesture-handler/issues/451#issuecomment-476444917
hope this comment can help you! @sapjax
