### ISSUE TITLE
Expo warns with "Cannot resolve the path to "react-stickynode" package."

### ISSUE THREAD

**Issue by desfero** [showtime-xyz/showtime-tab-view#7]
This error happens because `react-stickynode` is a dependency of `showtime-tab-view` which expo just blindly reads from `package.json` and tries to resolve the path to the package to see if it has some native modules to link.
Given that it's also in `peerDependencies` pnpm doesn't install the `react-stickynode` (as we don't have it installed too given we are only using ios/android part of the package).

**Comment by alantoa** [comment]
yeah, that's makes sense! i'll remove `react-stickynode` because it's not very useful.

**Comment by alantoa** [comment]
i just released a new version for this! 
https://github.com/showtime-xyz/showtime-tab-view/releases/tag/v0.1.4
